// workflow/demo.js — the controlled, deterministic live demo.
//
// The demo always runs on a known project, built fresh from:
//   demo/template/        project files (package.json, docs/cart_rules.md, src/checkout.js, …)
//   demo/cart.fixture.js  the known buggy implementation (never edited)
//   demo/bug_report.txt   the known bug report
// into runs/_demo-workspace/. Reset only ever touches that folder. It never touches
// uploaded, GitHub or local user workspaces.
//
// The demo uses the real IBM Bob provider. If Bob or the test environment is
// unavailable the demo refuses to start (or fails visibly). No fake results.

'use strict';

const fs   = require('fs');
const path = require('path');
const { DEMO_DIR, DEMO_WORKSPACE, RUNS_DIR } = require('./paths');
const ws = require('./workspace');
const { runProcess } = require('./proc');

const TEMPLATE = path.join(DEMO_DIR, 'template');
const FIXTURE = path.join(DEMO_DIR, 'cart.fixture.js');
const BUG_REPORT = path.join(DEMO_DIR, 'bug_report.txt');

const FIXTURE_HEADER = /^\/\/ src\/cart\.fixture\.js\r?\n\/\/ BUGGY reference implementation — do NOT edit this file\.\r?\n/;
const RESET_HEADER = '// src/cart.js\n// Reset to buggy baseline for this demo run.\n';

function bugReport() {
  return fs.readFileSync(BUG_REPORT, 'utf8').trim();
}

/** Build runs/_demo-workspace from the template + buggy fixture (header corrected). */
function resetWorkspace() {
  fs.rmSync(DEMO_WORKSPACE, { recursive: true, force: true });
  ws.copyProject(TEMPLATE, DEMO_WORKSPACE);
  const fixture = fs.readFileSync(FIXTURE, 'utf8');
  const cart = FIXTURE_HEADER.test(fixture) ? fixture.replace(FIXTURE_HEADER, RESET_HEADER) : RESET_HEADER + fixture;
  ws.ensureDir(path.join(DEMO_WORKSPACE, 'src'));
  fs.writeFileSync(path.join(DEMO_WORKSPACE, 'src', 'cart.js'), cart, 'utf8');
  return DEMO_WORKSPACE;
}

function ensureWorkspace() {
  if (!fs.existsSync(path.join(DEMO_WORKSPACE, 'src', 'cart.js'))) resetWorkspace();
  return DEMO_WORKSPACE;
}

let jestSmoke = null; // { ok, detail, at }

/** Run one trivial Jest test so "test environment could not start" is caught before Bob is used. */
async function jestSmokeTest() {
  if (jestSmoke && Date.now() - jestSmoke.at < 5 * 60 * 1000) return jestSmoke;
  const dir = path.join(RUNS_DIR, '_preflight');
  fs.rmSync(dir, { recursive: true, force: true });
  ws.ensureDir(path.join(dir, '__bugrep__'));
  fs.writeFileSync(path.join(dir, '__bugrep__', 'smoke.test.js'), "test('smoke', () => { expect(1 + 1).toBe(2); });\n");
  const runner = require('./testrunner');
  let res;
  try {
    const r = await runner.runTests(dir, '__bugrep__/smoke.test.js', { language: 'javascript', moduleType: 'commonjs' }, { stage: 'preflight' });
    res = r.outcome === 'pass' ? { ok: true, detail: 'Jest ran a smoke test' } : { ok: false, detail: (r.output || 'Jest did not run').split('\n')[0].slice(0, 160) };
  } catch (err) {
    res = { ok: false, detail: err.message };
  }
  fs.rmSync(dir, { recursive: true, force: true });
  jestSmoke = { ...res, at: Date.now() };
  return jestSmoke;
}

/**
 * Checks that do NOT use any Bob calls. Returns { ok, reason, checks:[{id,label,ok,detail}] }.
 */
async function preflight() {
  const checks = [];
  const add = (id, label, ok, detail) => checks.push({ id, label, ok: !!ok, detail: detail || '' });

  add('fixture', 'Demo buggy fixture exists', fs.existsSync(FIXTURE), 'demo/cart.fixture.js');
  add('template', 'Demo project template exists', fs.existsSync(path.join(TEMPLATE, 'package.json')), 'demo/template/');
  add('bug-report', 'Known bug report exists', fs.existsSync(BUG_REPORT), 'demo/bug_report.txt');
  const major = Number(process.versions.node.split('.')[0]);
  add('node', 'Node.js 18 or newer', major >= 18, `Node ${process.versions.node}`);
  let jestPath = null;
  try { jestPath = require.resolve('jest/bin/jest'); } catch { /* missing */ }
  add('jest', 'Jest is installed', !!jestPath, jestPath ? 'jest found' : 'run npm install in bugrep-ai');

  let writable = false;
  try {
    ws.ensureDir(RUNS_DIR);
    const probe = path.join(RUNS_DIR, `.write-test-${process.pid}`);
    fs.writeFileSync(probe, 'ok'); fs.unlinkSync(probe);
    writable = true;
  } catch { /* not writable */ }
  add('writable', 'Run folder is writable', writable, RUNS_DIR);

  let wsOk = false;
  try { ensureWorkspace(); wsOk = fs.existsSync(path.join(DEMO_WORKSPACE, 'src', 'cart.js')); } catch { /* failed */ }
  add('workspace', 'Controlled demo workspace ready', wsOk, 'runs/_demo-workspace');

  if (jestPath && writable) {
    const smoke = await jestSmokeTest();
    add('jest-runs', 'Test environment starts', smoke.ok, smoke.detail);
  } else {
    add('jest-runs', 'Test environment starts', false, 'skipped — Jest missing or folder not writable');
  }

  const bob = require('../agents/bob');
  const s = await bob.getStatus();
  add('bob', 'IBM Bob is available', s.operational, s.operational ? `IBM Bob ${s.version || ''}`.trim() : s.detail);

  const failed = checks.filter(c => !c.ok);
  let reason = null;
  if (failed.some(c => c.id === 'bob')) reason = 'IBM Bob is unavailable.';
  if (failed.some(c => ['jest', 'jest-runs', 'node'].includes(c.id))) reason = 'Test environment could not start.';
  if (!reason && failed.length) reason = failed[0].label + ' — failed.';
  return { ok: failed.length === 0, reason, checks };
}

module.exports = { preflight, resetWorkspace, ensureWorkspace, bugReport, RESET_HEADER };
